import { z } from 'zod';

/**
 * Single, validated source of runtime configuration.
 * Fail fast at boot rather than surfacing `undefined` deep inside a request.
 */
const EnvSchema = z.object({
  NODE_ENV: z.enum(['development', 'test', 'production']).default('development'),
  HOST: z.string().default('0.0.0.0'),
  PORT: z.coerce.number().int().min(1).max(65535).default(4000),
  LOG_LEVEL: z.enum(['fatal', 'error', 'warn', 'info', 'debug', 'trace', 'silent']).default('info'),

  /** Absolute or cwd-relative path to the SQLite file. `:memory:` is supported for tests. */
  DATABASE_PATH: z.string().default('./data/presight.sqlite'),

  /** Comma-separated list of allowed browser origins, or `*`. */
  CORS_ORIGIN: z.string().default('*'),

  /** Number of users generated by `npm run db:seed`. */
  SEED_USER_COUNT: z.coerce.number().int().min(1).max(1_000_000).default(25_000),
  SEED_RANDOM_SEED: z.coerce.number().int().default(20260830),

  /** Run migrate + seed-if-empty during server boot (handy for `docker compose up`). */
  AUTO_MIGRATE: z
    .enum(['true', 'false'])
    .default('true')
    .transform((v) => v === 'true'),
});

export type Env = z.infer<typeof EnvSchema>;

function load(): Env {
  const parsed = EnvSchema.safeParse(process.env);
  if (!parsed.success) {
    const issues = parsed.error.issues.map((i) => `  - ${i.path.join('.')}: ${i.message}`).join('\n');
    throw new Error(`Invalid environment configuration:\n${issues}`);
  }
  return parsed.data;
}

export const env: Env = load();
export const isProduction = env.NODE_ENV === 'production';
